# Generated by Django 5.1.2 on 2024-11-04 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("username", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=30, unique=True)),
                ("location", models.CharField(max_length=250)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("manager", "Manager"),
                            ("developer", "Developer"),
                            ("student", "Student"),
                        ],
                        max_length=30,
                    ),
                ),
                ("about", models.TextField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.company"
                    ),
                ),
            ],
        ),
    ]
